# ==========================================
# Configuración de la base de datos H2 (En memoria)
# ==========================================
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:taller20;DB_CLOSE_DELAY=-1

# ==========================================
# Parámetros recomendables
# ==========================================
# drop-and-create es perfecto para pruebas en memoria, crea las tablas al iniciar y las borra al apagar
quarkus.hibernate-orm.database.generation=drop-and-create 

# Para mostrar las consultas SQL en la consola y ver la magia del OneToOne
quarkus.hibernate-orm.log.sql=true  

# Comentamos el import.sql por ahora para que no intente ejecutar scripts de Postgres en nuestra base H2
#quarkus.hibernate-orm.sql-load-script=import.sql